Repository openinf/util-text, pull requests merged in 2022-10, with the labels that each got.

#125 fix(deps): specify supported node versions in pjson engines
  package.json
Labels: dependencies, deps-dev, javascript, author-ready

#127 fix(deps): rm jsdoc-to-markdown (vulnerable dep)
  README.hbs
  package-lock.json
  package.json
Labels: documentation, dependencies, build, deps-dev

#124 feat(index): add cyanify function
  index.d.ts
  index.ts
Labels: author-ready

#128 build(src,lib): properly build project/ignore build products
  .gitignore
  .nvmrc
  index.d.ts
  index.js
  index.test.js
  package-lock.json
  package.json
  src/declaration404.d.ts
  src/index.ts
  test/index.test.js
  tsconfig.base.json
  tsconfig.json
Labels: enhancement, build, javascript, author-ready
